# Generated by Django 5.1 on 2024-08-23 04:20

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('wallet_address', models.CharField(max_length=100, verbose_name='address')),
                ('testnet', models.BooleanField(default=True)),
                ('currency', models.CharField(default='Sepolia ETH', max_length=50)),
                ('txn_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('block_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=4, default=0.0001, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0001)])),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('confirmed', 'CONFIRMED'), ('failed', 'FAILED')], default='pending', max_length=50)),
                ('blockchain', models.CharField(default='ETHEREUM', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
