# Generated by Django 5.1 on 2024-08-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='block_hash',
        ),
        migrations.AddField(
            model_name='transaction',
            name='block_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
